Microverse "Hello World" Project with HTML-CSS feature branch Request Pull#1
efmomoh/Hello_World pull request #1
Opened 2023-03-22 20:49 UTC by efmomoh

2023-03-22 20:51 UTC, efmomoh commented
This is a basic HTML-CSS file that runs on web browsers

2023-03-23 07:50 UTC, binhussen requested changes
Hi @efmomoh,
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 07:50 UTC, binhussen commented on README.md
> +This project is [MIT](LICENSE) licensed.
- Great Job for customizing the readme with your information 👍 I think your MIT link has been broken, Kindly fix it, you can fix it by creating LICENSE.md with this [template](https://choosealicense.com/licenses/mit/)

2023-03-23 08:16 UTC, OyePriscilla approved these changes
Hi @efmomoh  👏 👏, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Linters check passed ✔️
Added HTML and CSS files ✔️ 
Made required changes ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 08:16 UTC, OyePriscilla commented on README.md
>  ### Tech Stack <a name="tech-stack"></a>
- [optional] Please kindly add the tech stacks (html, css) that you used in building this project, this will make your repo more informative. 👍

2023-03-24 23:35 UTC, merged